baseurl      = "https://hcc-613.sturcke.dev/"
languageCode = "en-us"
title        = "Erik · HCC 613"
theme        = "kaktus"

[params]
name        = "Erik J. Sturcke"
title       = "User Interface Prototyping and Development"
subtitle    = "UMBC · HCC 613 · SPRING 2016"
description = "UMBC class project blog of Erik J. Sturcke for HCC 613 – User Interface Prototyping and Development (Spring 2016)."
enableRSS   = true
bio         = "Front end programmer and occasional student."

[social]
twitter  = "https://www.twitter.com/carbonbox"
github   = "https://www.github.com/esturcke"
